apiVersion: v1
kind: Service
metadata:
  name: {{ template "jellyfin.fullname" . }}
  labels:
    app: {{ template "jellyfin.name" . }}
    chart: {{ template "jellyfin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8096
      protocol: TCP
      name: http
  selector:
    app: {{ template "jellyfin.name" . }}
    release: {{ .Release.Name }}
